package com.example.greendaodemo.create;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaodemo.table.StudentBeanTable;

import com.example.greendaodemo.create.StudentBeanTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentBeanTableDaoConfig;

    private final StudentBeanTableDao studentBeanTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentBeanTableDaoConfig = daoConfigMap.get(StudentBeanTableDao.class).clone();
        studentBeanTableDaoConfig.initIdentityScope(type);

        studentBeanTableDao = new StudentBeanTableDao(studentBeanTableDaoConfig, this);

        registerDao(StudentBeanTable.class, studentBeanTableDao);
    }
    
    public void clear() {
        studentBeanTableDaoConfig.clearIdentityScope();
    }

    public StudentBeanTableDao getStudentBeanTableDao() {
        return studentBeanTableDao;
    }

}
